### ISSUE TITLE
[feature] jupyter notebook integration

### ISSUE THREAD

**Issue by mu22le** [European-XFEL/h5glance#26]
I'd love to be able to use h5glance's lightweight hdf file preview in Jupyter notebook, skipping the step of having to create a small notebook every time. 

Ideally the library would be integrated in jupyter so that when I click on a hdf5 file in tree view it automatically shows the file structure using h5glance HTML interface. 

Do you see that as an interesting feature to develop?

**Comment by mu22le** [comment]
jupyterlab-hdf5 supposedly does something very similar (and more), but it only supports jupyterlab.

**Comment by takluyver** [comment]
I don't think the classic notebook interface has an extension point for opening different types of file in the file browser - as far as I know, it has hardcoded special handling to open notebooks & text files in their respective editors. If I'm wrong about that, or you can see a way to hack it in, I'm happy to hear about it.

I should say up front, though, that there are features h5glance deliberately doesn't have because of the context it's designed for. E.g. the HTML view has no way to view data, because in a notebook you can easily get the data with h5py and display it with just a couple of lines of code. There are other projects to make a complete HTML-based viewer for HDF5, like h5web (https://h5web.panosc.eu/ ), so this isn't a goal for h5glance.

**Comment by mu22le** [comment]
Thank you for the clarification. It's too bad that there is no easy way to integrate h4glance with jupyter, I think it would have been a useful addition.

**Comment by takluyver** [comment]
I'm happy to be proven wrong - it's been a few years since I was familiar with the Jupyter code, so it could easily have changed in the meantime, or I could have forgotten something. But that's my best guess.

**Comment by mu22le** [comment]
I found something similar to what I was looking for: [jupyterlab-hdf5](https://github.com/jupyterlab/jupyterlab-hdf5).

It requires Jupyter lab, which is more extensible, and does an impressive job, so far.
